const { NOTIFICATION_TYPES } = require("./notification-types");

const CHANNELS = Object.freeze({
  EMAIL: "EMAIL",
  TELEGRAM: "TELEGRAM"
});

const notificationChannelMap = Object.freeze({
  [NOTIFICATION_TYPES.VERIFY_EMAIL]: CHANNELS.EMAIL,
  [NOTIFICATION_TYPES.RESET_PASSWORD]: CHANNELS.EMAIL,
  [NOTIFICATION_TYPES.BOOKING_CONFIRMATION]: CHANNELS.EMAIL,
  [NOTIFICATION_TYPES.PAYMENT_SUCCESS]: CHANNELS.EMAIL,
  [NOTIFICATION_TYPES.BOOKING_CANCELLED]: CHANNELS.EMAIL,
  [NOTIFICATION_TYPES.PAYMENT_FAILED]: CHANNELS.TELEGRAM,
  [NOTIFICATION_TYPES.SYSTEM_ERROR]: CHANNELS.TELEGRAM,
  [NOTIFICATION_TYPES.RENTER_VERIFICATION_RESULT]: CHANNELS.TELEGRAM,
  [NOTIFICATION_TYPES.INVENTORY_ABNORMAL]: CHANNELS.TELEGRAM
});

function resolveChannelByType(type) {
  return notificationChannelMap[type] || null;
}

module.exports = {
  CHANNELS,
  notificationChannelMap,
  resolveChannelByType
};
