const NOTIFICATION_TYPES = Object.freeze({
  VERIFY_EMAIL: "VERIFY_EMAIL",
  RESET_PASSWORD: "RESET_PASSWORD",
  BOOKING_CONFIRMATION: "BOOKING_CONFIRMATION",
  PAYMENT_SUCCESS: "PAYMENT_SUCCESS",
  BOOKING_CANCELLED: "BOOKING_CANCELLED",
  PAYMENT_FAILED: "PAYMENT_FAILED",
  SYSTEM_ERROR: "SYSTEM_ERROR",
  RENTER_VERIFICATION_RESULT: "RENTER_VERIFICATION_RESULT",
  INVENTORY_ABNORMAL: "INVENTORY_ABNORMAL"
});

module.exports = {
  NOTIFICATION_TYPES
};
